name: Go

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: true
      run: make bin/opm

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: opm-linux-amd64
        path: bin/opm